# Generated by Django 6.0.6 on 2026-07-09 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('yahoo_symbol', models.CharField(max_length=30)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto'), ('gold', 'Gold'), ('forex', 'Forex')], max_length=20)),
                ('condition', models.CharField(choices=[('below', 'Below'), ('above', 'Above')], max_length=10)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('triggered', models.BooleanField(default=False)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
