# Generated by Django 6.0.6 on 2026-07-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='company',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
