# Generated by Django 6.0.6 on 2026-06-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='asset_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto'), ('gold', 'Gold'), ('forex', 'Forex')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='condition',
            field=models.CharField(choices=[('below', 'Below'), ('above', 'Above')], max_length=10),
        ),
    ]
