# Generated by Django 6.0.6 on 2026-07-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='triggered',
            field=models.BooleanField(default=False),
        ),
    ]
