# Generated by Django 6.0.6 on 2026-07-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alert_triggered'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
